DROP TABLE IF EXISTS TEACHER_X_STUDENT;
DROP TABLE IF EXISTS USER_X_SUBJECT;
DROP TABLE IF EXISTS PULPIT_X_DEPARTMENT;
DROP TABLE IF EXISTS SUBJECT;
DROP TABLE IF EXISTS "USER";
DROP TABLE IF EXISTS "GROUP";
DROP TABLE IF EXISTS SPECIALIZATION;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS EDUCATIONAL_STRUCTURE;


DROP DATABASE IF EXISTS TEST;
CREATE DATABASE TEST;


CREATE TABLE EDUCATIONAL_STRUCTURE (
  structure_id SERIAL PRIMARY KEY,
  structure_nm VARCHAR(100),
  foundation_dt DATE,
  pulpit_flg BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE DEPARTMENT (
  department_id SERIAL PRIMARY KEY,
  school_structure_id INT REFERENCES EDUCATIONAL_STRUCTURE (structure_id),
  department_nm VARCHAR(200),
  foundation_dt DATE NOT NULL
);

CREATE TABLE SPECIALIZATION (
  specialization_id INT PRIMARY KEY,
  specialization_nm VARCHAR(200) NOT NULL
);

CREATE TABLE "GROUP"(
  group_id SERIAL PRIMARY KEY,
  department_id INT REFERENCES DEPARTMENT (department_id) NOT NULL,
  specialization_id INT REFERENCES SPECIALIZATION (specialization_id) NOT NULL
);

CREATE TABLE "USER" (
  user_id SERIAL PRIMARY KEY,
  group_id INT REFERENCES "GROUP"(group_id),
  first_nm VARCHAR(50) NOT NULL,
  middle_nm VARCHAR(50),
  last_nm VARCHAR(50) NOT NULL,
  birdth_dt DATE NOT NULL,
  pulpit_structure_id INT REFERENCES EDUCATIONAL_STRUCTURE (structure_id),
  city_nm VARCHAR(50) NOT NULL,
  phone_no VARCHAR(12) CHECK (phone_no ~ '(^\+7[0-9]{10}$)?'),
  gender_code VARCHAR(1) NOT NULL,
  income_amt FLOAT CHECK (income_amt >= 0) DEFAULT 0.0,
  teacher_flg BOOLEAN NOT NULL
);

CREATE TABLE SUBJECT (
  subject_id SERIAL PRIMARY KEY,
  pulpit_structure_id INT REFERENCES EDUCATIONAL_STRUCTURE (structure_id) NOT NULL,
  subject_nm VARCHAR(100) NOT NULL
);

CREATE TABLE PULPIT_X_DEPARTMENT (
  pulpit_structure_id INT REFERENCES EDUCATIONAL_STRUCTURE (structure_id) NOT NULL,
  department_id INT REFERENCES DEPARTMENT (department_id) NOT NULL
);

CREATE TABLE USER_X_SUBJECT (
  user_id INT REFERENCES "USER" (user_id) NOT NULL,
  subject_id INT REFERENCES SUBJECT (subject_id) NOT NULL,
  lection_flg BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE TEACHER_X_STUDENT (
  teacher_user_id INT REFERENCES "USER" (user_id) NOT NULL,
  student_user_id INT REFERENCES "USER" (user_id) NOT NULL,
  lection_flg BOOLEAN NOT NULL DEFAULT FALSE
);
